export const USER_AUTH_PROPERTY = 'USER_AUTH_PROPERTY';
export const USER_PROFILE_PROPERTY = 'USER_PROFILE_PROPERTY';
export const CONSUMER_PROFILE_PROPERTY = 'CONSUMER_PROFILE_PROPERTY';
export const TELEMETRY_DATA_PROPERTY = 'TELEMETRY_DATA_PROPERTY';
export const CHAT_LOG_PROPERTY = 'CHAT_LOG_PROPERTY';
export const CONVERSATION_DATA_PROPERTY = 'CONVERSATION_DATA_PROPERTY';
